---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflared-tunnel-credentials
  namespace: cloudflared
spec:
  encryptedData:
    credentials.json: AgAz7q/khtU3O6iAMV5jRMA7DofOJOVZGJpI1vlfddas4NJSAMcuHbFKFhIp6G/1qovaBrVMZs/LY4vXY32/lgrFijqja9VNhc0EgfUorGWSuNh5GGXJYv4Y2m5hIrfIAJnVmsw9vDywlQV/8UHTmxVGkmTykL1pohNVr+/W6AuicKxMl0rEoE68hGDOcyzbSI5AWkAEDM/BkDqjIulGMduL5ou0BQypKDLUhUSltOCjA6hy2UH87EsLLpCpAEUqJuqlkiG45Z8mXujOqhIGCv0Pi/g3qDOARzIzdzu367r8o82YLIsfTcC0+dxUq4Phy+OX2Mp2zs7aGc/qmBpM74R1miK7pzLO+0G/LkKvZp+1/uhPV72hGRdySAqm+JdEPI+WprUBL34P/FdzopEf3ewfPUZtz159zKCv7RRSHroZ2E+z4/VXYKsBS55t3KZZYt1k5lW8IEqO5iRJ6PzQtmURaveG1Aprw9fTkoZrDhDnRDkhXpujAxOQTCW8maEMFLBced30wK495m/jro5X6ms7rPril/Rz9EuxjwSA0DN8PEIC9qbNkZwYKBY8RkQvXmvOGeAi+oOnc4bh2j0KT/MTx+1ZywlOVNkaWq0y8Yb6U7SWvaDAVohoyGAN0Ecy/q1oBdKI0sb2433TdNCYEiAbfVQVMrPGdBg0Ltm04pvr9Zqjo+H1w0cNX5uYSnFPWHjuwGy1jc3nFjpmDZRA98iB4pG/WBDqf9uyJ4E5xf/5PKYTLOW0CsxCDQ4p/PpOQXlgOTRPiTaE1SDUWnOjWiRp4r68azmqgqTcFdVJqWOSD0mf6DRea22qpGEkS88BYbUQIYQ/OsKRx+FlSd68CneFEmGJuNwUB6j5yoXaL9FRRvxEbdn+hRMDVN4UYM07xYmbYFFgXMy34mwHTTFjF5yxzfza+M9Es3NMbA1v4AGi
  template:
    metadata:
      name: cloudflared-tunnel-credentials
      namespace: cloudflared
