apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: authentik
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.goauthentik.io
    chart: authentik
    targetRevision: "2026.8.0"
    helm:
      releaseName: authentik
      values: |
        postgresql:
          enabled: true
          auth:
            existingSecret: authentik-creds
            secretKeys:
              adminPasswordKey: postgresql-password
              userPasswordKey: postgresql-password
        redis:
          enabled: true
        server:
          env:
            - name: AUTHENTIK_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: authentik-creds
                  key: secret_key
            - name: AUTHENTIK_POSTGRESQL__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: authentik-creds
                  key: postgresql-password
          ingress:
            enabled: true
            ingressClassName: traefik
            hosts:
              - auth.codeomelet.dev
        worker:
          env:
            - name: AUTHENTIK_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: authentik-creds
                  key: secret_key
            - name: AUTHENTIK_POSTGRESQL__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: authentik-creds
                  key: postgresql-password
  destination:
    server: https://kubernetes.default.svc
    namespace: authentik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
